### ISSUE TITLE
GHP doesn't work

### ISSUE THREAD

**Issue by Rudxain** [HammamiKhairi/New-Year-CountDown#5]
https://hammamikhairi.github.io/New-Year-CountDown says "Site not found". But [HTML Preview](http://htmlpreview.github.io/?https://github.com/hammamikhairi/New-Year-CountDown/blob/main/index.html) works, for some reason

**Comment by hammamikhairi** [comment]
Fixed it, the GHP is up ad running
`https://hammamikhairi.github.io/New-Year-CountDown/`
